"""
--- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...
If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...
Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....
You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2
This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..
So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?

Your puzzle answer was 6391.

The first half of this puzzle is complete! It provides one gold star: *


"""


class Knot(object):

    def __init__(self, length=1):
        self._position_x = 0
        self._position_y = 0
        self._length = length

    def positions(self):
        return self._position_x, self._position_y

    def move(self, direction):
        if direction == 'R':
            self._position_x = self._position_x + 1
        elif direction == 'L':
            self._position_x = self._position_x - 1
        elif direction == 'U':
            self._position_y = self._position_y + 1
        else:
            self._position_y = self._position_y - 1

    def requires_movement(self, head):
        x1, y1 = self.positions()
        x2, y2 = head.positions()
        return abs(x1 - x2) > self._length or abs(y1 - y2) > self._length

    def move_to(self, x, y):
        self._position_x = x
        self._position_y = y

    def __repr__(self):
        return f'(x:{self._position_x}, y:{self._position_y})'

    def pull(self, tail):
        tail_x , tail_y = tail.positions()
        head_x , head_y = self.positions()
        if self.requires_movement(tail):
            if abs(tail_x-head_x) <=1:
                tail_x = head_x
            elif head_x - tail_x == 2:
                tail_x +=1
            elif head_x - tail_x == -2:
                tail_x -= 1

            if abs(tail_y-head_y) <=1:
                tail_y = head_y
            elif head_y - tail_y == 2:
                tail_y += 1
            elif head_y - tail_y == -2:
                tail_y -= 1

        tail.move_to(tail_x, tail_y)





class Instruction(object):

    def __init__(self, *args):
        self.direction = args[0]
        self.quantity = int(args[1])

    def can_move(self):
        return self.quantity > 0

    def move(self):
        self.quantity = self.quantity - 1
        return self.direction


def simulate(instructions, knots=2):
    knots_array = []
    for knot in range(knots):
        knots_array.append(Knot())
    result = [knots_array[-1].positions()]
    for instruction in instructions:
        while instruction.can_move():
            head = knots_array[0]
            head.move(instruction.move())
            knot = head
            for i in range(1, len(knots_array)):
                next_knot = knots_array[i]
                if next_knot.requires_movement(knot):
                    actual_x, actual_y = next_knot.positions()
                    next_knot.move_to(old_x, old_y)
                    old_x, old_y = actual_x, actual_y
                    knot = next_knot

            tail = knots_array[-1]
            if tail.positions() not in result:
                result.append(tail.positions())
            print(knots_array)
    return result


def process(file_name):
    instructions = []
    with open(file_name, 'r') as file:
        for line in file:
            clean_line = line.strip()
            instructions.append(Instruction(*clean_line.split(' ')))
    result = simulate(instructions)
    print(len(result))


files = {'test': 'test.txt', 'prod': 'input.txt', "test2": "part2.txt"}

if __name__ == "__main__":
    mode = "test2"
    print(process(files[mode], "part2"))
